### ISSUE TITLE
support a dry run type option

### ISSUE THREAD

**Issue by ian-kelling** [dlenski/wtf#1]
I found it useful to run find, find many files, then do wtf -o /dev/null to preview the changes, then wtf -i if I'm satisfied. There should be a built in option which acts like -o /dev/null.

**Comment by dlenski** [comment]
Ian, thanks for the suggestion. How about `-0`/`--dry-run` for this purpose?

**Comment by ian-kelling** [comment]
Sounds great.

**Comment by dlenski** [comment]
Done in bd79d8567400b800e8bf9a23456724f0c3180f04. I used `os.devnull`, so hopefully it will work correctly on Windows too.
