### ISSUE TITLE
Bash completion

### ISSUE THREAD

**Issue by aryelgois** [dlenski/wtf#13]
Hello there

when I was being lazy and pressing `tab` to list the files, this happened:

```
$ wtf <TAB>
cut: /usr/share/misc/acronyms*: No such file or directory
-f
```

Even if I remove `wtf` from my PATH and try again, that happens. Could it be because of [wtf(6)](https://linux.die.net/man/6/wtf)? But I don't think it is installed..

**Comment by dlenski** [comment]
Looks like it is indeed because of `wtf(6)`, good catch. What distro are you running? What version of the bash-completion database?

**Comment by aryelgois** [comment]
I'm running Ubuntu Gnome 16.04, with bash completion 2.1

**Comment by cxw42** [comment]
I finally figured this out.  The [bash-completion](https://github.com/scop/bash-completion) package (at least as implemented on Cygwin) puts a completion for `wtf(6)` in `/usr/share/bash-completion/completions/wtf`.  That completion is then autoloaded for the command-line text `wtf`, regardless of whether `wtf(6)` is installed.

Per the [`bash-completion` FAQ](https://github.com/scop/bash-completion/blob/master/README.md#FAQ), you can override this by adding the following to your `.bashrc`:

    complete -o default -o bashdefault wtf

It works for me (Cygwin x64, bash 4.4.12(3)-release x64).  @dlenski would you be willing to mention this in the documentation next time you update (this) wtf?

(How to see where it searches for completions: start a fresh shell and do `set -x ; wtf <TAB>`.  Scroll back up and you will see it checking in various paths.)

**Comment by aryelgois** [comment]
@cxw42 thanks, that line solved!

**Comment by aryelgois** [comment]
I will create a pull request for the documentation. Should I write inside **Bugs**?
