### ISSUE TITLE
respect gitattributes

### ISSUE THREAD

**Issue by jeanluct** [dlenski/wtf#22]
When I commit a PDF file, it runs wtf on the PDF (I removed the `-q` switch in the hook):
```
> git add file.pdf
> git commit -m "test"
<stdin>:
	CHOPPED 9 lines with trailing space
	CHOPPED 0 blank lines at EOF
	no change to newline at EOF
	CHANGED 16 line endings which didn't match lf from first line
	WARNED ABOUT 0 lines with mixed tabs/spaces
```

This can mess up the PDF.  I understand that I can bypass the filter with -n, but wouldn't it be better for wtf to respect files explicitly declared as binary in `.gitattributes`?

Many thanks,

Jean-Luc

**Comment by dlenski** [comment]
> wouldn't it be better for wtf to respect files explicitly declared as binary in `.gitattributes`?

Yes, that'd be a good idea. :+1: 

Want to take a crack at a pull request to use [`git check-attr`](https://git-scm.com/docs/git-check-attr) to skip non-text files in the [pre-commit hook](https://github.com/dlenski/wtf/blob/master/pre-commit.careful)?

**Comment by jeanluct** [comment]
Ah, ok, I just wanted to check that I wasn't missing something obvious.  I'll see if I can get something working.  I didn't know about `check-attr`.

**Comment by dlenski** [comment]
I didn't either! I vaguely recall attempting to do this when I first wrote `wtf`, but not being able to come up with a reasonably simple way to parse `.gitattributes`.

Looks like git-check-attr was added in ~2.6.7 (3 years ago).

**Comment by jeanluct** [comment]
Ah!  I was about to try this out but saw your branch.  I tested it a bit and it seems to work fine.

Thanks!  This is very helpful.
