### ISSUE TITLE
Add option to report full crlf file

### ISSUE THREAD

**Issue by ian-kelling** [dlenski/wtf#4]
wtf has option to convert to crlf, but not report a full crlf file as a problem, only a mix of crlf and lf. git can (and looks like by default, but I haven't tested) report a full crlf file as a whitespace problem.

**Comment by dlenski** [comment]
How does git react to a file which is only _partially_ delimited with crlf, and partially with lf?

Perhaps an option like `---expect-eol ENDING` could report _any_ non-matching line-ending?

```
-E ENDING, --coerce-eol ENDING
--expect-eol ENDING
                      Coerce or report line endings not matching a specific type: crlf, lf, or
                      native (default none)
```
