### ISSUE TITLE
Add Space to Tab Conversion

### ISSUE THREAD

**Issue by hatzopoulos** [dlenski/wtf#6]
Any plans on adding "Space to tab conversion" as mentioned in the [todo section](https://github.com/dlenski/wtf#todo)?

It would be nice for wtf.py to also be able to convert leading _N_ spaces to tabs.

**Comment by dlenski** [comment]
We were discussing this in issues/#3, too. Patches, please :)

**Comment by hatzopoulos** [comment]
I will gladly create a PR for this. Stay tuned :+1:
